[package]
name = "mj_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
syn = "*"
quote = "*"
proc-macro2 = "*"
mj_base = { path = "../mj_base" }
j4rs = "0.17"