[package]
name = "mirai_j4rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "lib"] # cdylib 供 jvm_side 使用。

[dependencies]
contact_derive = { path = "./contact_derive" }
j4rs = { git = "https://github.com/astonbitecode/j4rs.git" }
j4rs_derive = { git = "https://github.com/astonbitecode/j4rs.git" }
num_enum = "0.7"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
serde_json = "1.0"
rand = "0.8"
#const_unit_poc = "*" # 该依赖的引入是一个巨大的错误。why: 这个应该交由用户处理。
# directories = "5.0"
# num_cpus = "^1.15"
# rust-crypto = "^0.2"
# ring = "^0.16"
# lazy_static = "^1.4"
# once_cell = "^1.16"
