[package]
name = "mirai_j4rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
j4rs = "*"
const_unit_poc = "*"
contact_derive = { path = "./contact_derive" }
num_enum = "*"
j4rs_derive = { git = "https://github.com/astonbitecode/j4rs.git" }
serde = { version = "*", features = ["derive"] }
directories = "5.0.1"
toml = "0.7"
serde_json = "1.0"
# num_cpus = "^1.15"
# rust-crypto = "^0.2"
# ring = "^0.16"
# lazy_static = "^1.4"
# once_cell = "^1.16"
