[package]
name = "mj_closures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
j4rs = "0.17"
j4rs_derive = "0.1"
mj_base = { path = "../mj_base" }
mj_macro = { path = "../mj_macro" }
