[package]
name = "mj_closure"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
j4rs = { workspace = true }
j4rs_derive = { workspace = true }
mj_base = { path = "../mj_base" }
mj_macro = { path = "../mj_macro" }
